#!/bin/bash

if [ x"$SHELL_DIR" = x ]
then
        SHELL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
fi

readonly ceph_dir=/var/lib/ceph
readonly osd_data_dir=$ceph_dir/osd
readonly osd_data_base="ceph"
readonly mon_dir=$ceph_dir/mon
readonly rgw_dir=$ceph_dir/radosgw

readonly config_file_local="local.conf"
readonly config_file_remote="remote.conf"
readonly config_file_dir_local="/etc/ceph"
readonly config_file_dir_remote="/etc/ceph"
readonly keyring_file_local="local.client.admin.keyring"
readonly keyring_file_remote="remote.client.admin.keyring"

readonly conf_dir=/etc/ceph
readonly ceph_conf=$conf_dir/ceph.conf
readonly tmp_dir=/tmp
readonly remote_tmp_dir=$tmp_dir/create_cluster
mkdir -p $remote_tmp_dir

#ceph log dir
readonly ceph_log_dir=/var/log/ceph 
mkdir -p $ceph_log_dir
readonly log_file_name="ceph_rbd_mirror.log"
readonly local_log_file=$ceph_log_dir/$log_file_name
readonly remote_log_file=$ceph_log_dir/$log_file_name
readonly local_ip=$(ifconfig eth1 | grep -E -o "inet addr:([[:digit:]]{1,3}\.){3}[[:digit:]]{1,3}"|cut -d':' -f2)
print_log=${print_log:-"yes"}
ECHO="echo -e"
SEG="\n"


# readonly all_quorum_ip_local=$(sudo ceph -s --cluster local\
# | egrep -o "\b([[:digit:]]{1,3}\.){3}[[:digit:]]{1,3}\b" 2>/dev/null)

# readonly all_quorum_ip_remote=$(sudo ceph -s --cluster remote\
# | egrep -o "\b([[:digit:]]{1,3}\.){3}[[:digit:]]{1,3}\b" 2>/dev/null)

# readonly local_leader_hostname=$(sudo ceph quorum_status --cluster local \
# | sed s/.*quorum_leader_name\":\"//g|sed s/\".*$//g 2>/dev/null)
# readonly local_leader_ipaddr=$(sudo ceph quorum_status  --cluster local \
# | sed s/^.*\"$local_leader_hostname\",\"addr\":\"//g|sed s/:.*$//g 2>/dev/null)

# readonly remote_leader_hostname=$(sudo ceph quorum_status --cluster remote \
# | sed s/.*quorum_leader_name\":\"//g|sed s/\".*$//g 2>/dev/null)
# readonly remote_leader_ipaddr=$(sudo ceph quorum_status  --cluster remote \
# | sed s/^.*\"$remote_leader_hostname\",\"addr\":\"//g|sed s/:.*$//g 2>/dev/null)

#1st param: level(ERROR, WARNING, INFO)
#2nd param: detail info
#3rd parma: print or not(yes/no)
function add_log()
{
	local level="$1"
	local info="$2"
	local date="[`date +"%m/%d %H:%M:%S"`]"
	local std_output=$3
	if [ x"$level" = x ] && [ x"$info" = x ]
	then
		echo "" >> $local_log_file
	else
		echo "$date $level $info" >> $local_log_file
	fi

	if [ x"$std_output" = x"yes" ]
	then
		echo "$level: $info"
	fi
}

function clear_log()
{
	echo "" > $local_log_file
}

#1st param: exit code(0/1)
#2nd param: result
#3rd param: detail info
#4th param: type(1=format, 0=unformat)
function my_exit()
{
	local exit_code=$1
	local result="$2"
	local details="$3"
	local ftype="$4"

	if [ x"$ftype" = x"0" ]
	then
		$ECHO "$details"
		add_log "$exit_code" "$details" no
	else
		$ECHO "Reslut:$result"
		$ECHO "Detail:$details"
		add_log "$exit_code" "Reslut:$result" no
		add_log "$exit_code" "Detail:$details" no
	fi
	
	exit $exit_code
}
